public class LoopDemo {
    
    public static void fordemo(){
        for(integer i=1;i<=10;i++){
            system.debug(i);
        }
    }
    public static void sumofnaturalnumber(integer n){
        integer i , sum =0 ;
        for(i=1;i<=n;i++){
            sum = sum*i;
        }
        system.debug('sum'+sum);
    }
    public static void tabledemo(integer n){
        for(integer i=1;i<=10;i++){
            system.debug(n*1);
        }
    }
    
}