public class Square {
         
    public static void addition() {
        Integer add,a=5,b=10;
         add = a+b;
        System.debug('Addition = ' +add);
    }
        public static void subtraction() {
        Integer sub,a=10,b=5;
         sub = a-b;
        System.debug('subtraction = ' +sub);
    
}
    public static void multiplication(integer a,integer b) {
        Integer mul;
         mul = a*b;
        System.debug('Multiplication = ' +mul);
    
}
}